name: SnapLoop
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    align_positioned: ^1.2.8
    animated_text_kit: ^2.5.1
    animations: ^1.1.2
    auto_route: ^0.6.9
    auto_size_text: ^2.1.0
    badges: ^1.1.4
    cached_network_image: ^2.3.3
    cloud_firestore: ^0.14.2
    connectivity: ^2.0.0
    contacts_service: ^0.4.6
    cupertino_icons: ^1.0.0
    device_preview: ^0.4.8
    email_validator: ^1.0.6
    firebase_messaging: ^7.0.3
    flappy_search_bar: ^1.7.2
    flip_card: ^0.4.4
    floating_action_bubble: ^1.1.2
    flutter_blurhash: ^0.5.0
    flutter_cache_manager: ^1.4.1
    flutter_form_builder: ^3.11.3
    flutter_image_compress: ^0.7.0
    flutter_keyboard_visibility: ^3.2.1
    flutter_launcher_icons: ^0.7.5
    flutter_local_notifications: ^1.4.4+2
    flutter_native_timezone: ^1.0.4
    flutter_secure_storage: ^3.3.4
    flutter_slidable: ^0.5.4
    flutter_spinkit: ^4.1.2+1
    flutter_typeahead: ^1.8.5
    font_awesome_flutter: ^8.8.1
    get_it: ^4.0.2
    google_fonts: ^1.1.0
    http: ^0.12.2
    image_picker: ^0.6.7+11
    injectable: ^1.0.2
    intl: ^0.16.1
    intl_phone_number_input: ^0.4.6+2
    intro_slider: ^2.3.1
    introduction_screen: ^1.0.9
    location: ^3.0.2
    logger: ^0.9.1
    mask_text_input_formatter: ^1.0.7
    observable_ish: ^2.1.4
    path_provider: ^1.6.18
    permission_handler: ^5.0.1+1
    persistent_bottom_nav_bar: ^2.0.5
    progress_dialog: ^1.2.4
    provider: ^4.3.2+2
    pull_to_refresh: ^1.6.2
    rxdart: ^0.24.1
    share: ^0.6.5+4
    shared_preferences: ^0.5.12+2
    shimmer: ^1.1.2
    simple_animations: ^2.2.3
    socket_io: ^0.9.4
    socket_io_client: ^0.9.11
    stacked: ^1.7.6
    stacked_hooks: ^0.1.3+1
    stacked_services: ^0.5.4+4
    sticky_headers: ^0.1.8+1
    timezone: ^0.5.9
    validators: ^2.0.1
    wakelock: ^0.2.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    auto_route_generator: ^0.6.6
    build_runner: ^1.10.0
    injectable_generator: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true
    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/
        - assets/memojis/
        - packages/timezone/data/2020a.tzf

    #   - images/a_dot_ham.jpeg
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    fonts:
        - family: Open Sans
          fonts:
              - asset: assets/fonts/Open_Sans/OpenSans-italic.ttf
              - asset: assets/fonts/Open_Sans/OpenSans-ExtraBoldItalic.ttf
              - asset: assets/fonts/Open_Sans/OpenSans-BoldItalic.ttf
                style: italic
              - asset: assets/fonts/Open_Sans/OpenSans-Bold.ttf
                weight: 500
              - asset: assets/fonts/Open_Sans/OpenSans-ExtraBold.ttf
                weight: 900
              - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
              - asset: assets/fonts/Open_Sans/OpenSans-SemiBold.ttf
                weight: 300
              - asset: assets/fonts/Open_Sans/OpenSans-Light.ttf
                weight: 100
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
