import 'package:SnapLoop/Model/user.dart';

/**
 * author: @sanchitmonga22
 */
final user = User(
    userID: "1",
    displayName: "Monga",
    email: "sanchitmonga22@gmail.com",
    score: 783,
    username: "sanchitmonga22",
    friendsIds: [
      "2",
      "3",
      "5"
    ],
    loopIDs: [
      "Loop1",
      "Loop2",
      "Loop3",
      "Loop4",
      "Loop20",
      "Loop6",
      "Loop7",
      "Loop8",
      "Loop9",
      "Loop10",
      "Loop11",
      "Loop12",
      "Loop13",
      "Loop14",
      "Loop15",
      "Loop16",
      "Loop17",
      "Loop18",
      "Loop19",
    ]);

final users = [
  User(
      friendsIds: ["1", "3"],
      userID: "2",
      displayName: "Baali",
      email: "aahishbali@gmail.com",
      score: 563,
      username: "Aahish",
      loopIDs: [
        "Loop1",
        "Loop2",
        "Loop3",
        "Loop4",
        "Loop20",
        "Loop5",
        "Loop6",
        "Loop7",
        "Loop8",
        "Loop9",
        "Loop10",
        "Loop11",
        "Loop12",
        "Loop13",
        "Loop14",
        "Loop15",
        "Loop16",
        "Loop17",
        "Loop18",
        "Loop19",
      ]),
  User(
      friendsIds: ["2", "1", "3"],
      userID: "3",
      displayName: "Gotti",
      email: "gottii@gmail.com",
      score: 753,
      username: "Gnandeep",
      loopIDs: [
        "Loop1",
        "Loop6",
        "Loop7",
        "Loop8",
        "Loop9",
        "Loop10",
        "Loop11",
        "Loop12",
        "Loop13",
        "Loop14",
        "Loop15",
        "Loop16",
        "Loop18",
        "Loop19",
      ]),
  User(
      friendsIds: ["5", "3"],
      userID: "4",
      displayName: "Anuj",
      email: "anushm@gmail.com",
      score: 143,
      username: "Anush",
      loopIDs: [
        "Loop2",
        "Loop3",
        "Loop4",
        "Loop20",
        "Loop5",
        "Loop6",
        "Loop7",
        "Loop8",
        "Loop9",
        "Loop16",
        "Loop17",
        "Loop19",
      ]),
  User(
      friendsIds: ["1", "4"],
      userID: "5",
      displayName: "Prekki",
      email: "aprekki@gmail.com",
      score: 53,
      username: "Aditya",
      loopIDs: [
        "Loop2",
        "Loop3",
        "Loop4",
        "Loop20",
        "Loop5",
        "Loop6",
        "Loop7",
        "Loop8",
        "Loop9",
        "Loop16",
        "Loop17",
        "Loop18",
        "Loop19",
      ]),
];
